### ISSUE TITLE
Stress test adding data to the tree

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/coniks-go#16] opened 2016-07-13 06:33 UTC
5ff85ad6ec6fd5214a9edc59232ca4e53a5d6199 is an indication that we should have a test that generates a large number of key/val pairs to set and retrieve from the tree.

**Comment by c633** [comment] 2016-07-13 06:53
That's right. I also had this idea last night. We should also add tests which involve all features of the library as well.

**Comment by Liamsi** [comment] 2016-07-29 09:00
As @arlolra pointed out by mail this is also about profiling:

>particularly automatically generated a lot of data to
stick in the tree and then profiling to see where the
bottlenecks may be / memory consumption.

**Comment by Liamsi** [comment] 2016-07-29 10:02
Here is a list of missing tests (per package):

merkletree
- pad.TB

crypto:
- Digest
- MakeRand

utils:
- ToBits

In general only the success cases are well tested. Branches where we `panic`/return an `error` or return a negative result on a check like `crypto.Verify` aren't covered by tests most of the time.

Just wanted to leave this here for discussion.

**Comment by masomel** [comment] 2016-07-29 18:09
> In general only the success cases are well tested. Branches where we panic/return an error or return a negative result on a check like crypto.Verify aren't covered by tests most of the time.

This seems like an issue to me. I think we should definitely be covering failure cases as well. This will be especially important if/when we create a common test suite for ``coniks-go`` and ``coniks-java`` (I think we discussed this in #25).

Another thing I wanted to open up for discussion was whether we should be using a code coverage  measurement tool like Coveralls or Codecov.io? These are the main ones I've seen, I'm sure there are more out there.

**Comment by arlolra** [comment] 2016-07-29 18:25
> Another thing I wanted to open up for discussion was whether we should be using a code coverage measurement tool like Coveralls or Codecov.io?

Couldn't hurt, and [goveralls](https://github.com/mattn/goveralls) seems pretty straightforward.

**Comment by masomel** [comment] 2016-07-29 18:39
> Couldn't hurt, and goveralls seems pretty straightforward.

Cool! I've authorized Coveralls to access the coniks-sys repos. I'll go set up goveralls.

**Comment by Liamsi** [comment] 2016-07-29 19:18
Good idea. Also thought about that. After the changes the code coverage is already quite high. I'm not necessarily a friend of aiming for 100% code coverage, though. But goveralls seems like a good idea anyways!

**Comment by masomel** [comment] 2016-07-29 20:11
So I've set up goveralls. I wasn't able to get it to work without testing each package and subpackage individually, so now we just have to remember to add each new package to the YAML file.

**Comment by Liamsi** [comment] 2016-07-29 21:29
Besides some tests, I've added Benchmarks for a first indicator if sth. is slow (and needs to be profiled).

It's still pretty much WIP but feel free to have an early look into it and/or test it on your machine(s). Maybe the first benchmark (`BenchmarkCreateLargePAD`) can be removed as recreating the tree happens rarely (?). The 2nd benchmark (`BenchmarkLookUpFromLargeDirectory`) is measuring (single) lookups in a large tree. 
I think it looks OK: For a tree with (only) 1000 entries the lookup takes 566781 ns (~0.00056 s) 10000 entries a lookup takes around 1098726 ns (around 0.0010 s); for a tree with 100000 entries it takes also around 1166422 ns (0,001167 s); for 250000 entries it takes around 1207726 ns (0,0012077 s). For even larger trees the creation of the tree consumes so much time that it doesn't make sense to Benchmark the lookups anymore. Also, wouldn't in practice the key-value pairs stored in a db (independent from the tree structure), such that lookups won't necessarily happen from memory (like in the tests)?

**Comment by arlolra** [comment] 2016-07-30 00:48
> So I've set up goveralls.

Nice work @masomel

**Comment by c633** [comment] 2016-07-30 01:52
> Maybe the first benchmark (BenchmarkCreateLargePAD) can be removed as recreating the tree happens rarely (?). 

I think we can replace this test with tree clone tests? Since this task must be performed in each epoch. I imagine the scenario would be creating an empty tree then inserting a lot of records (e.g., 1000 per epoch) then cloning the tree; repeating this task for a large number of time. 

> Also, wouldn't in practice the key-value pairs stored in a db (independent from the tree structure), such that lookups won't necessarily happen from memory (like in the tests)?

Maybe I didn't get your idea completely. But I think we do need to perform the lookup from memory, not only to retrieve the user's data blob but also to check if the given user is on the tree (i.e., registered with the keyserver). 

> For a tree with (only) 1000 entries the lookup takes 566781 ns (~0.00056 s) 10000 entries a lookup takes around 1098726 ns (around 0.0010 s); for a tree with 100000 entries it takes also around 1166422 ns (0,001167 s); for 250000 entries it takes around 1207726 ns (0,0012077 s).

Great work!

> For even larger trees the creation of the tree consumes so much time that it doesn't make sense to Benchmark the lookups anymore (all on recent mac book pro). 

I will give it a try on my machine.

**Comment by c633** [comment] 2016-07-30 19:22
Should we perform the evaluation as described in the paper section 5?

**Comment by Liamsi** [comment] 2016-07-31 12:29
> I think we can replace this test with tree clone tests? Since this task must be performed in each epoch. I imagine the scenario would be creating an empty tree then inserting a lot of records (e.g., 1000 per epoch) then cloning the tree; repeating this task for a large number of time.

Sounds good.

> Should we perform the evaluation as described in the paper section 5?

Makes sense to me. Parts of the evaluation deal with network communication, though. In order for this to be realistic we could consider other means (derterLab/similar test beds).

**Comment by Liamsi** [comment] 2016-07-31 12:55
> Maybe I didn't get your idea completely. But I think we do need to perform the lookup from memory, not only to retrieve the user's data blob but also to check if the given user is on the tree (i.e., 

I though there must be a way to do a single lookup without holding the whole tree in memory (but I didn't think it through). Currently it seems like creating/querying/updating a large tree takes very long and consumes a lot of memory (even with quite modest tree sizes with only 100000 entries). I'll investigate this further in the following week. Maybe the Benchmarks I'm doing aren't the best/right approach, too.

**Comment by Liamsi** [comment] 2016-07-31 17:49
I did some profiling (when benchmarking pad.Update in tree with 100,000 entries). 
It seems interesting that most of the time is spent doing scalar multiplication `edwards25519.FeMul`  and most memory is consumed in `crypto.Digest`. 

Memory usage: https://imagebin.ca/v/2pyfIzrKD7li
cpu usage: https://imagebin.ca/v/2pyg7GQ4sDCs
(both files can be downloaded as .svg files and viewed in a browser)

**Comment by masomel** [comment] 2016-07-31 22:01
> It's still pretty much WIP but feel free to have an early look into it and/or test it on your machine(s). 

I'll run some benchmarks on my lab machine, hopefully early this week and can report the results back to you, too. Really nice work on the benchmarks so far, @Liamsi! Would be cool to post some results in a wiki at some point.

> Should we perform the evaluation as described in the paper section 5? 

If you'd like, I could try to run some benchmarks on a (similar) setup to the one in the paper. We ran them on one of the servers in my group's cluster, and I could probably get that set up again.

**Comment by Liamsi** [comment] 2016-08-02 06:35
I think (if there aren't further suggestions what should be benchmarked) this is ready to be reviewed in PR #43. 

My conclusion(s) regarding the profiling: We should refactor the memory intensive hashing (currently done by `crypto.Digest`) by using `hash.Write` whenever it makes sense (and only sum at the very end). Currently, all bytes are collected and `Digest` is called at the end. 
Other than that, `LookUp` seems fast; and when creating the tree using `Set` the crypto (field operations) seem to use a big part of the cpu time (especially `edwards25519.FeMul`). I'm not sure if can do about these operations though. 

>If you'd like, I could try to run some benchmarks on a (similar) setup to the one in the paper. We ran them on one of the servers in my group's cluster, and I could probably get that set up again.

@masomel I think that makes a lot of sense to compare both implementations but ism't very urgent.

**Comment by c633** [comment] 2016-08-02 06:56
> Currently, all bytes are collected and Digest is called at the end. 

Can you make it clearer? I think there is not much memory allocation here, except when we call `hash.Write`. Maybe the memory overhead because of 1) how we pass the arguments and 2) we have a long list of arguments (when hashing the leaf nodes). What do you think?

**Comment by Liamsi** [comment] 2016-08-02 07:40
>>Currently, all bytes are collected and Digest is called at the end.

> Can you make it clearer?

I thought all data is collected and than `Digest`ed at the end. Looking through the code, I see this is not the case. Sorry for the noise. Still we should experiment if we can reduce the memory consumption here. At least the 2 points you mentioned are worth to experiment with.

**Comment by Liamsi** [comment] 2016-08-02 10:08
Using `h.Write` instead of `crypto.Digest` in `emptyNode.Hash` and `userLeafNode.Hash` and removing the additional `[]byte()` conversion where obsolete reduces the total memory consumption spent while hashing (in the exactly the same example namely `BenchmarkPADUpdate100K`) from 253.6 MB to 175.7 MB. I opened a separate issue for this: #51.

We should also keep in mind that we want devs to specify their own hashing scheme (see #50).

**Comment by Liamsi** [comment] 2016-08-02 12:03
Pushed the changes from the above comment to branch [hash_experiment](https://github.com/coniks-sys/coniks-go/tree/hash_experiment) in https://github.com/coniks-sys/coniks-go/commit/d128e43a10111bb6f9efa9ae80647f794e9b2bad (in case you want to reproduce the benchmark/comparison)

**Comment by masomel** [comment] 2016-08-02 16:15
> I think that makes a lot of sense to compare both implementations but this isn't very urgent I guess.

No, it's not particularly urgent, especially since the Java implementation we used for our benchmarks in the paper is now out of date.

**Comment by Liamsi** [comment] 2016-08-04 19:49
closed by #54

**Closed by Liamsi** 2016-08-04 19:49 UTC
Labels: testing
